DROP database IF EXISTS EmployeeDB;

CREATE database IF NOT EXISTS `EmployeeDB`;
use `EmployeeDB`;

CREATE TABLE `EMPLOYEE` (
  `EMPID` int(11) NOT NULL AUTO_INCREMENT,
  `EMPNAME` varchar(45),
  `DOB` DATE,
  `SALARY` int(11),
  `AGE` int(11),
  PRIMARY KEY (`EMPID`)
) ;


CREATE TABLE `USERS` (
  `UID` int(11) NOT NULL AUTO_INCREMENT,
  `USERNAME` varchar(45),
  `PASSWORD` varchar(45),
  PRIMARY KEY (`UID`)
) ;

CREATE TABLE `PRODUCT` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `NAME` varchar(45),
  `PRICE` DECIMAL(7,2),
  PRIMARY KEY (`ID`)
) ;

INSERT INTO `EMPLOYEE` (`EMPNAME`,`DOB`,`SALARY`, `AGE`) VALUES ('John Doe', '1969-06-09', 2000, 20);
INSERT INTO `EMPLOYEE` (`EMPNAME`,`DOB`,`SALARY`, `AGE`) VALUES ('Jane Doe','2000-08-08', 40000, 30);
INSERT INTO `EMPLOYEE` (`EMPNAME`,`DOB`,`SALARY`, `AGE`) VALUES ('Bob Ross','1956-12-12', 400, 35);
INSERT INTO `EMPLOYEE` (`EMPNAME`,`DOB`,`SALARY`, `AGE`) VALUES ('Blake Martin','1999-02-07', 90000, 19);
INSERT INTO `USERS` (`USERNAME`,`PASSWORD`) VALUES ('Pranav','abc');
INSERT INTO `PRODUCT` (`NAME`,`PRICE`) VALUES ('Apple',1.33);
INSERT INTO `PRODUCT` (`NAME`,`PRICE`) VALUES ('Banana',2.56);
INSERT INTO `PRODUCT` (`NAME`,`PRICE`) VALUES ('PC',2000.56);


SELECT * FROM PRODUCT WHERE ID>0;
